### ISSUE TITLE
Make group matching case-insensitive

### ISSUE THREAD

**Issue by bezborodow** [michaeldyrynda/laravel-ldap#1]
Under `vendor/dyrynda/laravel-ldap/src/Http/Middleware/LdapMiddleware.php`, line 61 in `ldapUserDisallowed()`

When Superloop used this package in the CRM, they had a problem initially with case-sensitivity.

The config variable for `laravel_ldap.allowed_groups` was using lowercase `cn=`, as opposed to the server sending back `CN=`, resulting in failed authorisation. It might make sense to make this case-insensitive.

**Comment by michaeldyrynda** [comment]
Was it the middleware that rejected, or was it the query scope on authentication? Should be trivial to update, regardless.

**Comment by michaeldyrynda** [comment]
Give the updated middleware in `feature/case-insensitive-group-matching` a go and see if that works a bit better.

**Comment by michaeldyrynda** [comment]
I've done some testing with this and it seems to work fine if i play with the case of the allowed groups. I'm not certain exactly how this will behave within adldap2 in terms of case-sensitivity, but authentication seems to work ok.

**Comment by bezborodow** [comment]
I got `ErrorExceptionUndefined variable: allowedGroups in LdapMiddleware.php (line 65)`

**Comment by michaeldyrynda** [comment]
Give it another `git pull` - I fixed that up in a subsequent commit

**Comment by bezborodow** [comment]
Okay, testing passed -- works for me.

I tested with lowercase CN in my .env file.
